/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * FastAPI
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult
} from '@tanstack/react-query';

import type {
  HTTPValidationError,
  UserCreate
} from '../../model';





/**
 * @summary Create New User
 */
export type createNewUserUsersPostResponse200 = {
  data: UserCreate
  status: 200
}

export type createNewUserUsersPostResponse422 = {
  data: HTTPValidationError
  status: 422
}

export type createNewUserUsersPostResponseSuccess = (createNewUserUsersPostResponse200) & {
  headers: Headers;
};
export type createNewUserUsersPostResponseError = (createNewUserUsersPostResponse422) & {
  headers: Headers;
};

export type createNewUserUsersPostResponse = (createNewUserUsersPostResponseSuccess | createNewUserUsersPostResponseError)

export const getCreateNewUserUsersPostUrl = () => {


  

  return `/users/`
}

export const createNewUserUsersPost = async (userCreate: UserCreate, options?: RequestInit): Promise<createNewUserUsersPostResponse> => {
  
  const res = await fetch(getCreateNewUserUsersPostUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      userCreate,)
  }
)

  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
  
  const data: createNewUserUsersPostResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as createNewUserUsersPostResponse
}
  



export const getCreateNewUserUsersPostMutationOptions = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createNewUserUsersPost>>, TError,{data: UserCreate}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof createNewUserUsersPost>>, TError,{data: UserCreate}, TContext> => {

const mutationKey = ['createNewUserUsersPost'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createNewUserUsersPost>>, {data: UserCreate}> = (props) => {
          const {data} = props ?? {};

          return  createNewUserUsersPost(data,fetchOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type CreateNewUserUsersPostMutationResult = NonNullable<Awaited<ReturnType<typeof createNewUserUsersPost>>>
    export type CreateNewUserUsersPostMutationBody = UserCreate
    export type CreateNewUserUsersPostMutationError = HTTPValidationError

    /**
 * @summary Create New User
 */
export const useCreateNewUserUsersPost = <TError = HTTPValidationError,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createNewUserUsersPost>>, TError,{data: UserCreate}, TContext>, fetch?: RequestInit}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createNewUserUsersPost>>,
        TError,
        {data: UserCreate},
        TContext
      > => {
      return useMutation(getCreateNewUserUsersPostMutationOptions(options), queryClient);
    }
    